baseurl = "https://satooru.sakura.ne.jp/docs/"
DefaultContentLanguage = "ja"
title = "SatooRu note"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
author = false
publishDir = "docs"

[Params]
  subtitle = "なぎ"
  logo = "img/pg-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "SatooRu"
  github = "SatooRu65536"
  twitter = "SatooRu_65536"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true